backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "menu"
    label: "Menu Items"
    folder: "content/menu"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Starters", "Main Courses", "Desserts", "Beverages"]}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
  
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Hero Title", name: "hero_title", widget: "string"}
          - {label: "Hero Subtitle", name: "hero_subtitle", widget: "string"}
          - {label: "Hero Image", name: "hero_image", widget: "image"}
          - {label: "About Title", name: "about_title", widget: "string"}
          - {label: "About Content", name: "about_content", widget: "markdown"}
          - {label: "About Image", name: "about_image", widget: "image"}
      
      - file: "content/contact.md"
        label: "Contact Information"
        name: "contact"
        fields:
          - {label: "Address", name: "address", widget: "string"}
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Opening Hours", name: "hours", widget: "markdown"}
